spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL JDBC 驱动类名
    url: jdbc:mysql://localhost:3306/coffeebean_detect  # 数据库连接URL，指定数据库名 coffeebean_detect
    username: root    # 数据库用户名
    password: bape050622  # 数据库密码
  web:
    resources:
      static-locations: classpath:/static/,file:./detectImages/

  redis:
    host: localhost     # Redis 主机地址
    port: 6379          # Redis 端口
    password: bape050622  # Redis 密码，如果无密码可省略

file:
  # 文件上传配置
  upload-dir: ${FILE_UPLOAD_DIR:uploads}
  # 默认上传目录为相对路径 "uploads"，可通过环境变量 FILE_UPLOAD_DIR 覆盖为绝对路径
  detect-dir: detectImages   # 保存目录（相对项目根目录）

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 是否开启数据库字段下划线到实体属性驼峰命名的自动映射，true表示开启
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # MyBatis 日志实现类，将 SQL 输出到控制台，方便调试
    global-config:
        db-config:
          id-type=auto:

  global-config:
    db-config:
      logic-delete-field: isDelete   # 逻辑删除字段名，对应数据库中标识删除状态的字段
      logic-delete-value: 1           # 逻辑删除时字段值，1表示已删除
      logic-not-delete-value: 0       # 未删除的字段值，0表示未删除

server:
  port: 8080            # 应用运行端口号
  servlet:
    context-path: /api  # 应用上下文路径，所有请求都会以 /api 开头

coze:
  bot-id: 7565069280355106867   # Bot ID，替换为你的 Bot ID
  pat: sat_2q0OG90CM7wmcHPuwmt02ch8H9r38rrrnpxhHS6tzHaZ6SBCRTDJCGL6oA9FeCXL
  # Bot PAT（访问令牌），用于身份验证和调用接口

detection:
  python-exe: venv/bin/python3
  # Python 解释器路径，可写系统 Python 或虚拟环境 Python
  # Windows 上可能是 python 或虚拟环境路径 venv\Scripts\python.exe
  # Mac 上可以是系统 Python 或虚拟环境路径 /path/to/venv/bin/python3

  pythonInterpreterPath: /Users/coconut/Desktop/咖啡豆项目/coffee-bean-detect/venv/bin/python3
  # Python 解释器绝对路径，供项目调用 Python 脚本时使用

  inferScriptPath: /Users/coconut/Desktop/咖啡豆项目/coffee-bean-detect/scripts/infer.py
  # Python 推理脚本绝对路径

  infer-script: scripts/infer.py
  # Python 推理脚本相对项目目录路径

  labels-file: scripts/labels.txt
  # 标签文件路径，相对项目目录，存储缺陷豆类别信息
